#!/usr/bin/env python3
"""Write src/data/site-catalog.json — public catalog source of truth."""
import json
from pathlib import Path

UPDATED = "2026-09-03"
ROOT = Path(__file__).resolve().parents[1]

def item(**kwargs):
    defaults = {
        "last_updated": UPDATED,
        "marketplace_url": None,
        "cta": "request_availability",
        "price_status": "not_published",
        "planning_price_usd": None,
        "status": "offering_review",
        "license": "One-time family license (planned)",
        "delivery": "Digital access after an approved purchase route, or physical kit when listed",
        "format": "Digital-first guided curriculum",
        "duration": "Published at offering review",
        "age_range": "See Shop by Age",
        "outcomes": [],
        "included": [],
        "not_included": ["Odyssey checkout on this site", "Program-account collection", "A claim that this SKU is already TEFA-listed"],
        "best_fit": [],
        "not_ideal": ["Anyone needing a live marketplace purchase today"],
        "how_families_use": [],
        "requirements": ["Adult facilitator or supervisor as noted on the product page"],
        "faq": [
            {"q": "Can I buy this on this website?", "a": "No. This website does not process TEFA payments or collect program-account details."},
            {"q": "When is the verified price shown?", "a": "Final marketplace eligibility and verified price are shown only for the exact SKU published in Odyssey."},
        ],
    }
    defaults.update(kwargs)
    return defaults

pathways = [
    item(
        sku="PS-CL-2495", title="Career Launch & Entrepreneurship", kind="pathway",
        department="Curriculum pathways", pathway="Career readiness",
        age_range="Ages 13–17 / grades 9–12", duration="36 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="Employability, workplace projects, and a student venture portfolio across a full year.",
        outcomes=["Practice workplace communication", "Plan a small student venture", "Build a portfolio of completed projects"],
        included=["36-week sequence", "Employability and communication modules", "Project-planning assignments", "Venture/portfolio capstone prompts", "Facilitator notes"],
        not_included=["Business formation, EIN, or legal filing", "Guaranteed income", "Physical studio hardware unless a kit is listed separately", "Odyssey checkout on this site"],
        best_fit=["Upper-high-school career credit", "Student building a real portfolio"],
        not_ideal=["Families needing a live TEFA checkout today", "Anyone seeking guaranteed job placement"],
        how_families_use=["Treat it as a year-long lab with weekly facilitator check-ins."],
        requirements=["Adult facilitator", "Computer access for portfolio work"],
        status="offering_review", price_status="planning_listing", planning_price_usd=2495,
        image="images/photo-career.jpg", cta="request_availability",
    ),
    item(
        sku="PS-IL-1995", title="Independent Living & Financial Foundations", kind="pathway",
        department="Curriculum pathways", pathway="Independent living",
        age_range="Ages 14–18 / grades 8–12", duration="30 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="Banking, housing, food, transportation, and household decisions as practical life-skill learning.",
        outcomes=["Practice household money decisions", "Run weekly home systems", "Document a living-skills year"],
        included=["30-week sequence with weekly lesson map", "Banking, housing, food, transportation modules", "Parent/facilitator notes", "Practice sheets for budgets and bills"],
        not_included=["Physical tools, groceries, or rent money", "Therapy, counseling, or medical services", "Odyssey checkout on this site"],
        best_fit=["Teen who needs household money systems before leaving home", "Homeschool practical-skills year"],
        not_ideal=["Anyone seeking clinical or therapeutic services"],
        how_families_use=["One weekly household lab plus a money practice sheet."],
        requirements=["Adult facilitator", "Access to household routines for practice (no purchase of tools required)"],
        status="offering_review", price_status="planning_listing", planning_price_usd=1995,
        image="images/photo-independent-living.jpg", cta="request_availability",
    ),
    item(
        sku="PS-AI-1695", title="AI Literacy & Digital Leadership", kind="pathway",
        department="Curriculum pathways", pathway="Digital judgment",
        age_range="Ages 11–17 / grades 6–12", duration="24 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="How modern tools work, how to question their output, and parent-supervised digital judgment.",
        outcomes=["Explain what a model is and where it fails", "Practice prompt-and-check", "Complete one parent-supervised useful tool"],
        included=["24-week sequence", "Offline-first lessons", "Verification, privacy, and bias discussion scripts", "Capstone: one small useful tool, parent-supervised"],
        not_included=["Unsupervised chatbot accounts", "Student data sent to public tools as part of the license", "Hardware"],
        best_fit=["Family that will not hand a child an open chatbot unsupervised"],
        not_ideal=["Unsupervised app-only use"],
        how_families_use=["Parent sits with the learner for judgment practice, not open chat."],
        requirements=["Adult supervision for any live-tool practice"],
        status="offering_review", price_status="planning_listing", planning_price_usd=1695,
        image="images/photo-ai-literacy.jpg", cta="request_availability",
    ),
    item(
        sku="PS-SR-2295", title="Structured Reading Support Pathway", kind="pathway",
        department="Curriculum pathways", pathway="Reading",
        age_range="Ages 8–14 / grades 3–8", duration="36 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="Decoding, fluency, vocabulary, and comprehension with facilitator scripts. Curriculum — not therapy.",
        outcomes=["Practice decoding and fluency", "Build vocabulary and comprehension routines", "Use facilitator scripts at home"],
        included=["36-week reading sequence", "Facilitator scripts", "Progress-check sheets"],
        not_included=["Speech therapy, dyslexia diagnosis, or clinical treatment", "School IEP services", "A claim of medical or therapeutic outcome"],
        best_fit=["Parent-led support at home", "Language-arts credit with a weekly map"],
        not_ideal=["Anyone seeking a clinical diagnosis or therapy substitute"],
        how_families_use=["Short daily reading practice with an adult using the scripts."],
        requirements=["Adult or tutor facilitator"],
        status="offering_review", price_status="planning_listing", planning_price_usd=2295,
        image="images/photo-reading.jpg", cta="request_availability",
    ),
    item(
        sku="PS-RR-2495", title="Real-World Readiness Year", kind="pathway",
        department="Curriculum pathways", pathway="Coordinated readiness",
        age_range="Ages 11–17 / grades 6–12", duration="36 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="One coordinated year map: career, money, independent living, and digital judgment.",
        outcomes=["Follow one year pacing map", "Cover four practical domains without four separate licenses"],
        included=["36-week coordinated map", "Career, money, independent-living, and digital-judgment units", "Facilitator notes"],
        not_included=["Four extra licenses (this is one combined license)", "Physical kits unless purchased as separate offerings"],
        best_fit=["Family that wants one year plan instead of four separate buys"],
        not_ideal=["Anyone needing four standalone licenses"],
        how_families_use=["One weekly block covering the coordinated map."],
        requirements=["Adult facilitator"],
        status="offering_review", price_status="planning_listing", planning_price_usd=2495,
        image="images/photo-readiness.jpg", cta="request_availability",
    ),
    item(
        sku="PS-IF-0299", title="Interview & First Job Prep", kind="pathway",
        department="Curriculum pathways", pathway="Career readiness",
        age_range="Ages 14–18 / grades 9–12", duration="8 weeks",
        format="Digital-first guided curriculum", license="One-time digital family license",
        delivery="Digital family access after the exact SKU is listed in Odyssey",
        purpose="Resumes, interview practice, and first-paycheck basics. Short on-ramp before a longer pathway.",
        outcomes=["Draft a resume", "Practice interview prompts", "Read a first-paycheck example"],
        included=["8-week lesson map", "Resume and application worksheets", "Interview practice prompts", "First-paycheck reading sheet"],
        not_included=["Job placement or guaranteed hire", "Physical interview clothing", "A live kit dollar price"],
        best_fit=["Teen applying for a first job this semester"],
        not_ideal=["Anyone expecting guaranteed employment"],
        how_families_use=["Eight weeks of short practice before Independent Living or Career Launch."],
        requirements=["Adult reviewer for resume drafts"],
        status="offering_review", price_status="not_published", planning_price_usd=None,
        image="images/photo-interview.jpg", cta="request_availability",
    ),
]

kits = [
    ("PS-PR-101", "Home & Repair Tool Roll", "Practical & Trade", "d01", "Ages 11–17", "images/home-and-repair-tool-roll.svg", "Household repair practice with adult supervision.", "practical life skills"),
    ("PS-PR-102", "Money & First Job Kit", "Practical & Trade", "d01", "Ages 11–17", "images/money-and-first-job-kit.svg", "Money habits and first-job paperwork practice.", "money habits"),
    ("PS-PR-103", "Kitchen & Provision Kit", "Practical & Trade", "d01", "Ages 9–17", "images/kitchen-and-provision-kit.svg", "Kitchen routines and provision planning.", "independent living"),
    ("PS-SC-201", "Situation Handling Deck", "Situation Handling & Self-Command", "d02", "Ages 8–17", "images/situation-handling-deck.svg", "Practice respectful communication and conflict navigation as life-skill learning.", "self-command"),
    ("PS-SC-202", "Focus & Energy System", "Situation Handling & Self-Command", "d02", "Ages 8–17", "images/focus-and-energy-system.svg", "Organization, time, and self-discipline practice.", "organization"),
    ("PS-SC-203", "Self-Advocacy Workbook", "Situation Handling & Self-Command", "d02", "Ages 11–17", "images/self-advocacy-workbook.svg", "Practice stating needs clearly and respectfully.", "self-advocacy"),
    ("PS-SC-204", "Interview & First Job Prep Kit", "Situation Handling & Self-Command", "d02", "Ages 14–17", "images/interview-and-first-job-prep-kit.svg", "Physical/print kit companion for interview practice.", "career readiness"),
    ("PS-SC-205", "Adulting Launch Kit", "Situation Handling & Self-Command", "d02", "Ages 14–18", "images/adulting-launch-kit.svg", "Household and personal-responsibility launch practice.", "independent living"),
    ("PS-CS-301", "Graphic Design Bench", "Design & Motion Studio", "d03", "Ages 11–17", "images/graphic-design-bench.svg", "Design and making practice.", "design"),
    ("PS-CS-302", "Motion & Video Kit", "Design & Motion Studio", "d03", "Ages 11–17", "images/motion-and-video-kit.svg", "Motion and video-making practice.", "creativity"),
    ("PS-CS-303", "Skill-to-Income Pack", "Design & Motion Studio", "d03", "Ages 13–17", "images/skill-to-income-pack.svg", "Practice turning a skill into a testable offer. Not a guaranteed-income program.", "entrepreneurship"),
    ("PS-AT-401", "AI Literacy Bench Kit", "AI & Emerging Tech Bench", "d04", "Ages 11–17", "images/ai-literacy-bench-kit.svg", "Hands-on companion to digital-judgment lessons.", "AI literacy"),
    ("PS-AT-402", "Electronics & Robotics Starter", "AI & Emerging Tech Bench", "d04", "Ages 11–17", "images/electronics-and-robotics-starter.svg", "Intro making with electronics, adult-supervised.", "emerging technology"),
    ("PS-AT-403", "3D Design & Fabrication Intro", "AI & Emerging Tech Bench", "d04", "Ages 13–17", "images/3d-design-and-fabrication-intro.svg", "Intro 3D design and making.", "design"),
    ("PS-HS-501", "Weekly Evidence Binder", "Homeschool Essentials", "d05", "Ages 3–12", "images/core-subjects-workbook-set.svg", "Weekly evidence binder for work samples, attendance notes, and homeschool documentation.", "organization"),
    ("PS-HS-502", "Homeschool Assessment & Portfolio Kit", "Homeschool Essentials", "d05", "Planner / educator", "images/homeschool-assessment-and-portfolio-kit.svg", "Evidence and portfolio organization for planners.", "organization"),
    ("PS-HS-503", "Daily Supply Restock Box", "Homeschool Essentials", "d05", "Ages 3–12", "images/daily-supply-restock-box.svg", "Consumable restock concept for daily work. Not in the TEFA pathway packet list.", "organization"),
    ("PS-HS-504", "Art & Craft Foundations Kit", "Homeschool Essentials", "d05", "Ages 3–8", "images/art-and-craft-foundations-kit.svg", "Art and craft foundations with adult supervision.", "creativity"),
]
kit_items = []
for sku, title, dept, _anchor, age, img, purpose, skill in kits:
    kit_items.append(item(
        sku=sku, title=title, kind="kit", department=dept, pathway=skill,
        age_range=age, duration="Published at offering review",
        format="Planned physical kit", license="One-time family license (planned)",
        delivery="Physical kit after the exact SKU is listed; packing list publishes at offering review",
        purpose=purpose,
        outcomes=[f"Practice {skill} with adult support"],
        included=["Planned kit contents and facilitator notes — final packing list publishes at offering review"],
        not_included=["Verified marketplace price", "Unsupervised hazardous tool use", "Odyssey checkout on this site"],
        best_fit=["Homeschool practical-skills block", "Family wanting a hands-on companion to a pathway"],
        how_families_use=["Use as a supervised project block, not as a live checkout item."],
        image=img, status="offering_review", price_status="not_published", cta="request_availability",
    ))

books = [
    item(
        sku="GEN-BK-001", title="The Vulturian", kind="book",
        department="Books", pathway="Reading",
        age_range="Pending metadata", duration="n/a",
        format="Book — format pending", license="Pending",
        delivery="Printing and fulfillment source pending",
        purpose="Confirmed title. Author credit, ISBN, price, format, description, cover, and printing source remain pending.",
        included=["Title is confirmed"],
        not_included=["ISBN", "Verified price", "Print-ready cover", "TEFA listing"],
        status="planning_concept", price_status="not_published",
        image="images/photo-vulturian.jpg", cta="ask_concept",
    ),
    item(
        sku="GEN-CB-101", title="Future Founders", kind="book",
        department="Books", pathway="Entrepreneurship",
        age_range="Pending", duration="n/a", format="Coloring-book concept",
        license="Pending", delivery="Not created",
        purpose="Working-title coloring book concept. Not for sale.",
        status="planning_concept", image="images/photo-future-founders.jpg", cta="ask_concept",
    ),
    item(
        sku="GEN-CB-102", title="Tools & Trades", kind="book",
        department="Books", pathway="Practical life skills",
        age_range="Pending", duration="n/a", format="Coloring-book concept",
        license="Pending", delivery="Not created",
        purpose="Working-title coloring book concept. Not for sale.",
        status="planning_concept", image="images/photo-tools-trades.jpg", cta="ask_concept",
    ),
    item(
        sku="GEN-CB-103", title="Big Feelings, Big Wins", kind="book",
        department="Books", pathway="Self-command",
        age_range="Pending", duration="n/a", format="Coloring-book concept",
        license="Pending", delivery="Not created",
        purpose="Working-title coloring book concept. Practical feelings vocabulary — not therapy.",
        status="planning_concept", image="images/photo-big-feelings.jpg", cta="ask_concept",
    ),
    item(
        sku="RC-CC-0169", title="Calm & Clear", kind="book",
        department="Books", pathway="Self-command",
        age_range="All ages coloring", duration="n/a",
        format="Paperback coloring book (Royal Collexions retail record)",
        license="Retail title — not a TEFA pathway packet item",
        delivery="Royal Collexions owns the retail master record. No checkout on this site.",
        purpose="50 bold, large-print mandalas. Direct-retail record only — not presented as a TEFA offering.",
        included=["Retail coloring-book title owned by Royal Collexions"],
        not_included=["TEFA marketplace listing", "Checkout on PreparationStation.org"],
        status="planning_concept", price_status="not_published",
        image="images/photo-calm-clear.jpg", cta="ask_concept",
    ),
]

free = [
    item(
        sku="PS-FR-BUDGET", title="Budget planner", kind="free_resource",
        department="Free resources", pathway="Money habits",
        age_range="Planner / family", duration="Single worksheet",
        format="Free printable HTML", license="Free educational resource",
        delivery="Open on this site",
        purpose="Plan income and expenses.",
        status="free_resource", price_status="none",
        image="images/photo-money-job.jpg", cta="open_printable",
        canonical_url="https://preparationstation.org/resources/budget-planner",
        resource_path="resources/budget-planner.html",
    ),
    item(
        sku="PS-FR-PAY", title="First paycheck", kind="free_resource",
        department="Free resources", pathway="Money habits",
        age_range="Ages 14–18", duration="Single worksheet",
        format="Free printable HTML", license="Free educational resource",
        delivery="Open on this site",
        purpose="Understand take-home pay.",
        status="free_resource", price_status="none",
        image="images/photo-interview.jpg", cta="open_printable",
        canonical_url="https://preparationstation.org/resources/first-paycheck",
        resource_path="resources/first-paycheck.html",
    ),
    item(
        sku="PS-FR-SAVE", title="Savings challenge", kind="free_resource",
        department="Free resources", pathway="Money habits",
        age_range="Family", duration="Single worksheet",
        format="Free printable HTML", license="Free educational resource",
        delivery="Open on this site",
        purpose="Track a savings target.",
        status="free_resource", price_status="none",
        image="images/photo-money-job.jpg", cta="open_printable",
        canonical_url="https://preparationstation.org/resources/savings-challenge",
        resource_path="resources/savings-challenge.html",
    ),
    item(
        sku="PS-FR-BIZ", title="Business idea", kind="free_resource",
        department="Free resources", pathway="Entrepreneurship",
        age_range="Ages 13–17", duration="Single worksheet",
        format="Free printable HTML", license="Free educational resource",
        delivery="Open on this site",
        purpose="Shape a testable offer.",
        status="free_resource", price_status="none",
        image="images/photo-career.jpg", cta="open_printable",
        canonical_url="https://preparationstation.org/resources/business-idea",
        resource_path="resources/business-idea.html",
    ),
]

for it in pathways + kit_items:
    it["canonical_url"] = f"https://preparationstation.org/products/{it['sku']}"
for it in books:
    it["canonical_url"] = f"https://preparationstation.org/products/{it['sku']}"

data = {
    "schema_version": 1,
    "updated_at": UPDATED,
    "operator": "Nationwide Acquisitions, LLC",
    "brand": "Preparation Station",
    "dba": "Preparation Station",
    "canonical_site": "https://preparationstation.org/",
    "canonical_catalog_url": "https://preparationstation.org/catalog",
    "support_email": "Hello@preparationstation.org",
    "sales_email": "Sales@preparationstation.org",
    "help_email": "Support@preparationstation.org",
    "phone": "682.253.5459",
    "mailing_address": "13101 Preston Rd Suite 110, Dallas, Texas 75240",
    "response_commitment": "Complete requests are acknowledged within one business day.",
    "vendor_status": "Nationwide Acquisitions, LLC is an approved TEFA Marketplace vendor. Each offering is reviewed separately in Odyssey.",
    "items": pathways + kit_items + books + free,
}
out = ROOT / "src" / "data" / "site-catalog.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(data, indent=2) + "\n")
print("wrote", out, "items", len(data["items"]))
